version: '3.2'
services:
  php-fpm:
    build: ./php
    ports:
      - "9000:9000"
    stdin_open: true
    tty: true
    links:
      - mysql-db:mysql-db
    volumes:
      - ../app:/data/www:rw
      - /var/www/html/:/usr/local/apache2/htdocs/:ro
      - ./php/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ../logs/php-fpm:/var/log/php-fpm:rw
    restart: always
    command: php-fpm

  httpd:
    build: ./httpd
    depends_on:
      - php-fpm
    stdin_open: true
    tty: true
    links:
      - php-fpm:php-fpm
    volumes:
      - ../app:/data/www:rw
      - /var/www/html/:/usr/local/apache2/htdocs/:ro
      - ./httpd/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./httpd/conf/extra/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf:ro
      - ../logs/httpd:/var/log/httpd
    ports:
      - "80:80"
        #      - "8080:8080"
      #- "444:443"
    restart: always
    #command: httpd -k restart

  mysql-db:
      build: ./mysql
      ports:
        - "3306:3306"
      volumes:
        - ../data/mysql/:/var/lib/mysql/:rw
        - ../logs/mysql/:/var/lib/mysql-logs/:rw
        - ./mysql/conf:/etc/mysql:ro
          #- ./mysql/conf/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
          #- ./mysql/conf/mysql.conf.d/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf:ro
      environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_DATABASE: dev
        MYSQL_USER: root
        MYSQL_PASSWORD: 123456
      restart: always
      command: "--character-set-server=utf8"
